runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /public
  static_dir: public

- url: /api/v(.?)/(users|files|tokens|groups).*
  script: handlers.\2.app

- url: /.*
  script: views.index.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
