runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /api/v(.?)/(.*)/(.*)
  script: handlers.\2.app

- url: /api/v(.?)/(.*)
  script: handlers.\2.app

- url: /.*
  script: handlers.main.app
